"""init

Revision ID: c322043c1ad9
Revises: 
Create Date: 2026-01-21 14:11:14.968187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c322043c1ad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_ledger_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('entry_type', sa.Enum('COMMISSION_EARNED', 'COMMISSION_ADJUST', 'COMMISSION_REVERSE', 'PAYOUT_PENDING', 'PAYOUT_SENT', 'PAYOUT_FAILED', 'PAYOUT_REFUND', 'DISPUTE_HOLD', 'DISPUTE_RELEASE', 'NOTE', name='commission_ledger_entry_type'), nullable=False),
    sa.Column('status', sa.Enum('POSTED', 'VOIDED', 'RECONCILED', name='commission_ledger_status'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_delta', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('order_item_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_provider', sa.String(length=40), nullable=True),
    sa.Column('payment_ref', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('related_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(is_voided = 0 AND status <> 'voided') OR (is_voided = 1 AND status = 'voided')", name='ck_comm_ledger_void_consistency'),
    sa.CheckConstraint("currency <> ''", name='ck_comm_ledger_currency_nonempty'),
    sa.CheckConstraint('amount <= 999999999999.99 AND amount >= -999999999999.99', name='ck_comm_ledger_amount_range'),
    sa.CheckConstraint('available_delta <= 999999999999.99 AND available_delta >= -999999999999.99', name='ck_comm_ledger_avail_range'),
    sa.CheckConstraint('version >= 1', name='ck_comm_ledger_version_gte_1'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_entry_id'], ['commission_ledger_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_comm_ledger_actor_created', ['actor_user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_comm_ledger_actor_currency_created', ['actor_user_id', 'currency', 'created_at'], unique=False)
        batch_op.create_index('ix_comm_ledger_order_actor', ['order_id', 'actor_user_id'], unique=False)
        batch_op.create_index('ix_comm_ledger_payref_actor', ['payment_ref', 'actor_user_id'], unique=False)
        batch_op.create_index('ix_comm_ledger_type_actor_created', ['entry_type', 'actor_user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_payment_provider'), ['payment_provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_payment_ref'), ['payment_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_related_entry_id'), ['related_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_entries_status'), ['status'], unique=False)

    op.create_table('commission_payouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'SENT', 'FAILED', 'CANCELED', 'RECONCILED', name='commission_payout_status'), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency <> ''", name='ck_comm_payout_currency_nonempty'),
    sa.CheckConstraint('fee_amount >= 0', name='ck_comm_payout_fee_nonneg'),
    sa.CheckConstraint('gross_amount >= 0', name='ck_comm_payout_gross_nonneg'),
    sa.CheckConstraint('net_amount >= 0', name='ck_comm_payout_net_nonneg'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_payouts', schema=None) as batch_op:
        batch_op.create_index('ix_comm_payout_provider_ref', ['provider', 'provider_ref'], unique=False)
        batch_op.create_index('ix_comm_payout_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payouts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payouts_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payouts_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payouts_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payouts_provider_ref'), ['provider_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payouts_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_commission_payouts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_payouts_updated_at'), ['updated_at'], unique=False)

    op.create_table('user_preferred_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('brand', sa.String(length=40), nullable=False),
    sa.Column('last4', sa.String(length=8), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(provider_code) >= 2', name='ck_upp_code_len'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_preferred_payment_user')
    )
    with op.batch_alter_table('user_preferred_payments', schema=None) as batch_op:
        batch_op.create_index('ix_upp_user_code', ['user_id', 'provider_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferred_payments_provider_code'), ['provider_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferred_payments_user_id'), ['user_id'], unique=False)

    op.create_table('affiliate_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aff_code', sa.String(length=80), nullable=False),
    sa.Column('sub_code', sa.String(length=120), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(aff_code) >= 1', name='ck_aff_click_aff_nonempty'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_clicks', schema=None) as batch_op:
        batch_op.create_index('ix_aff_clicks_aff_created', ['aff_code', 'created_at'], unique=False)
        batch_op.create_index('ix_aff_clicks_aff_sub_created', ['aff_code', 'sub_code', 'created_at'], unique=False)
        batch_op.create_index('ix_aff_clicks_prod_created', ['product_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_aff_code'), ['aff_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_sub_code'), ['sub_code'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=700), nullable=False),
    sa.Column('alt', sa.String(length=180), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index('ix_media_created_active', ['created_at', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_media_kind_active_deleted', ['kind', 'is_active', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_product_id'), ['product_id'], unique=False)
        batch_op.create_index('ix_media_product_sort', ['product_id', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_scope'), ['scope'], unique=False)
        batch_op.create_index('ix_media_scope_kind_active', ['scope', 'kind', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_sha256'), ['sha256'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('subtitle', sa.String(length=120), nullable=True),
    sa.Column('badge', sa.String(length=24), nullable=True),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.Column('cta_text', sa.String(length=30), nullable=True),
    sa.Column('cta_url', sa.String(length=240), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_active'), ['active'], unique=False)
        batch_op.create_index('ix_offers_active_sort', ['active', 'sort_order'], unique=False)
        batch_op.create_index('ix_offers_product', ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_sort_order'), ['sort_order'], unique=False)
        batch_op.create_index('ix_offers_starts_ends', ['starts_at', 'ends_at'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('title_snapshot', sa.String(length=200), nullable=False),
    sa.Column('sku_snapshot', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('line_total >= 0', name='ck_order_items_line_total_nonneg'),
    sa.CheckConstraint('qty >= 1', name='ck_order_items_qty_ge_1'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_items_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_order_items_order_created', ['order_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_order_items_product_created', ['product_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)

    op.create_table('product_categories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_table('product_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=700), nullable=False),
    sa.Column('poster_url', sa.String(length=700), nullable=True),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_media_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_media_sort_order'), ['sort_order'], unique=False)

    op.create_table('product_tags',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    with op.batch_alter_table('campaign_sends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_sends_to_email'), ['to_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_sends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_sends_to_email'))

    op.drop_table('product_tags')
    with op.batch_alter_table('product_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_media_sort_order'))
        batch_op.drop_index(batch_op.f('ix_product_media_product_id'))

    op.drop_table('product_media')
    op.drop_table('product_categories')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index('ix_order_items_product_created')
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index('ix_order_items_order_created')
        batch_op.drop_index(batch_op.f('ix_order_items_created_at'))

    op.drop_table('order_items')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index('ix_offers_starts_ends')
        batch_op.drop_index(batch_op.f('ix_offers_sort_order'))
        batch_op.drop_index(batch_op.f('ix_offers_product_id'))
        batch_op.drop_index('ix_offers_product')
        batch_op.drop_index('ix_offers_active_sort')
        batch_op.drop_index(batch_op.f('ix_offers_active'))

    op.drop_table('offers')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_sha256'))
        batch_op.drop_index('ix_media_scope_kind_active')
        batch_op.drop_index(batch_op.f('ix_media_scope'))
        batch_op.drop_index('ix_media_product_sort')
        batch_op.drop_index(batch_op.f('ix_media_product_id'))
        batch_op.drop_index('ix_media_kind_active_deleted')
        batch_op.drop_index(batch_op.f('ix_media_kind'))
        batch_op.drop_index(batch_op.f('ix_media_is_active'))
        batch_op.drop_index(batch_op.f('ix_media_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_media_created_at'))
        batch_op.drop_index('ix_media_created_active')

    op.drop_table('media')
    with op.batch_alter_table('affiliate_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_sub_code'))
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_product_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_created_at'))
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_aff_code'))
        batch_op.drop_index('ix_aff_clicks_prod_created')
        batch_op.drop_index('ix_aff_clicks_aff_sub_created')
        batch_op.drop_index('ix_aff_clicks_aff_created')

    op.drop_table('affiliate_clicks')
    with op.batch_alter_table('user_preferred_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferred_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferred_payments_provider_code'))
        batch_op.drop_index('ix_upp_user_code')

    op.drop_table('user_preferred_payments')
    with op.batch_alter_table('commission_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_payouts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_commission_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_commission_payouts_public_id'))
        batch_op.drop_index(batch_op.f('ix_commission_payouts_provider_ref'))
        batch_op.drop_index(batch_op.f('ix_commission_payouts_provider'))
        batch_op.drop_index(batch_op.f('ix_commission_payouts_currency'))
        batch_op.drop_index(batch_op.f('ix_commission_payouts_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_commission_payouts_created_at'))
        batch_op.drop_index('ix_comm_payout_status_created')
        batch_op.drop_index('ix_comm_payout_provider_ref')

    op.drop_table('commission_payouts')
    with op.batch_alter_table('commission_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_status'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_related_entry_id'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_public_id'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_posted_at'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_payment_ref'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_payment_provider'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_order_id'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_entry_type'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_currency'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_entries_actor_user_id'))
        batch_op.drop_index('ix_comm_ledger_type_actor_created')
        batch_op.drop_index('ix_comm_ledger_payref_actor')
        batch_op.drop_index('ix_comm_ledger_order_actor')
        batch_op.drop_index('ix_comm_ledger_actor_currency_created')
        batch_op.drop_index('ix_comm_ledger_actor_created')

    op.drop_table('commission_ledger_entries')
    # ### end Alembic commands ###
